Building a basic CRM: step one
astoliarenko/webix-jet-test-project-1 pull request #1
Opened 2021-10-11 16:11 UTC by astoliarenko

2021-10-11 18:02 UTC, kullias commented on sources/views/editpopup.js
> +			view: "popup",
лучше модальное окно с хедером (в который и пойдет заголовок окна)
сейчас можно создать ситуацию, при которой в открытой на редактирование форме валидные данные сходу будут подсвечены красным

2021-10-11 18:03 UTC, kullias commented on sources/views/editpopup.js
> +								btnSave,
по мокапу кнопки выровнены, лучше так и сделать

2021-10-12 09:14 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +			if (list.count() > 0) {
list.count() не может быть меньше 0, а если он будет равен 0, то if все равно не выйдет в true, так как 0 это false, так что по итогу ты можешь написать просто
`if (list.count()) {`

2021-10-12 09:15 UTC, uladzislaukumakou commented on sources/views/editpopup.js
> +			click: () => {
эту функцию отсюда надо вынести в отдельную функцию внутри класса и здесь ее просто вызывать. иначе нагромождение webix верстки и логики получается. очень тяжело читать все это

2021-10-12 09:20 UTC, uladzislaukumakou commented on sources/views/editpopup.js
> +			activityCopy.DueDate = webix.Date
ты в коллекции activities, в схеме уже конвертируешь дату из строки в формат Date, зачем тут еще раз?
Time, кстати, тоже можешь создавать в схеме. все равно ты перед отправкой его удаляешь

2021-10-13 09:14 UTC, kullias reviewed
главный тулбар только над меню, должен быть всегда виден

2021-10-13 16:01 UTC, uladzislaukumakou requested changes

2021-10-13 16:01 UTC, uladzislaukumakou commented on sources/views/contacts.js
> +				onAfterSelect: (id) => {
да, нужно вообще во всех файлах повыносить функции в методы класса. если функция больше 2-ух строк и она находится внутри webix вертски, то такое уже очень тяжело читать

2021-10-26 10:50 UTC, merged