Building a basic CRM: step two
astoliarenko/webix-jet-test-project-1 pull request #2
Opened 2021-10-31 23:15 UTC by astoliarenko

2021-11-01 12:10 UTC, kullias commented on sources/views/contactsViews/form.js
> +				.setValues({src: res});
фотка не сохраняется в контакт

2021-11-01 12:10 UTC, kullias commented on sources/views/contactsViews/form.js
> +				.setValues({src: res});
в поле в базе должна быть строка
в строку эту можно записать вот такую штуку https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs картинку в нее преобразовать
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL результат потом будет удобно использовать везде где эту фотку надо будет показывать

2021-11-01 12:10 UTC, kullias commented on sources/views/contactsViews/form.js
> +		}
- открываем форму на редактирование
- нажимаем Add contact
- id сбрасывается (то есть форма вроде как собирается позволить нам создать новый контакт), но форма не очищается от старых значений
- в итоге если нажать save, то эти же данные сохранятся под новым айди

2021-11-01 12:10 UTC, kullias commented on sources/views/contactsViews/form.js
> +					template: obj => `<img class="contacts-form-img" src=${obj.src || "./sources/img/man.png"}>`,
obj.Photo
а то фотка не показывается, если она есть в базе

2021-11-01 12:53 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +				.setValues({src: res});
я просто забыл в значение поля Photo вписать это src  в форме

2021-11-01 13:58 UTC, uladzislaukumakou approved these changes

2021-11-01 16:02 UTC, kullias requested changes

2021-11-01 16:02 UTC, kullias commented on sources/views/contactsViews/form.js
> +					this.loadFile(obj);
поскольку метод возврашает false то и тут return не надо забывать

2021-11-01 16:06 UTC, astoliarenko commented on sources/views/contactsViews/details.js
> +		// возможно нужно будет поменять ui
это старый коммент.. я его в самом начале вроде писал, ui вроде и поменялось потом, не помню уже

2021-11-01 16:12 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +							view: "textarea",
это я видимо скопировал поле из editWindow (там по макапу было похоже на textarea одно  поле), а потом не изменил на "text". Изменю

2021-11-01 16:16 UTC, astoliarenko commented on sources/views/contactsViews/files.js
> +					sort: "string"
понял

2021-11-01 16:21 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +					this.loadFile(obj);
все равно забуду return)

2021-11-01 16:22 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +					this.loadFile(obj);
onBeforeFileAdd: obj => this.loadFile(obj)

2021-11-01 16:22 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +					this.loadFile(obj);
бунт)

2021-11-01 16:24 UTC, astoliarenko commented on sources/views/activitiesViews/editwindow.js
>  		return false;
мне линтер подсвечивал что хочет return

2021-11-01 16:27 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +					if (this.hideInfo) {
ну да, так короче

2021-11-01 16:51 UTC, astoliarenko commented on sources/views/activitiesViews/editwindow.js
>  		const date = formValues.DateObj;
да, есть такое. попробую разобраться

2021-11-01 17:42 UTC, kullias requested changes

2021-11-01 17:42 UTC, kullias commented on sources/views/contactsViews/form.js
> -							view: "textarea",
высоту нету необходимости для text задавать, она по умолчанию в самый раз

2021-11-01 17:42 UTC, kullias commented on sources/views/contactsViews/form.js
> +					this.app.callEvent(constants.EVENTS.SELECT_CONTACT, [contactsCollection.getLastId()]);
res.id, где res - то чем резолвится промис - аргумент фунrции в then

2021-11-01 17:42 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					if (id) this.filter("#ContactID#", id);
![Selection_999(364)](https://user-images.githubusercontent.com/31205423/139715686-de0c60b1-5206-4f32-827b-b330e2a59453.png)

2021-11-01 17:42 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					if (id) this.filter("#ContactID#", id);
this - это что?
не торопись ты так. покликай хоть приложение перед коммитом)

2021-11-01 18:06 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> -							view: "textarea",
понял

2021-11-01 18:12 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +					this.app.callEvent(constants.EVENTS.SELECT_CONTACT, [contactsCollection.getLastId()]);
Да, понял, исправил. но в моем случае ведь тоже все сработает, тк getLastId от коллекции точно будет уже id нового элемента

2021-11-01 18:20 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +					if (id) this.filter("#ContactID#", id);
view таблицы, а нужен this.getRoot()

2021-11-01 20:57 UTC, astoliarenko commented on sources/views/activitiesViews/editwindow.js
>  		const date = formValues.DateObj;
в условии на сохранение просто стоит && а надо ||  -----    if (!form.validate() || !form.isDirty()) return false;

2021-11-02 09:17 UTC, kullias commented on sources/views/contactsViews/form.js
> +					this.app.callEvent(constants.EVENTS.SELECT_CONTACT, [contactsCollection.getLastId()]);
будет, но зачем вызывать метод, чтобы его найти, если у нас уже есть айди?

2021-11-02 09:19 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +					this.app.callEvent(constants.EVENTS.SELECT_CONTACT, [contactsCollection.getLastId()]);
это да

2021-11-02 09:49 UTC, kullias commented on sources/views/activitiesViews/editwindow.js
>  		const date = formValues.DateObj;
но форму по клику на сейв не закрывать все равно жестоко, если валидные данные, а чел просто ничего не изменил

2021-11-02 09:49 UTC, kullias commented on sources/views/activitiesViews/editwindow.js
>  		const date = formValues.DateObj;
еще кстати, я не заметила раньше, но окно это стоит сделать модальным
иначе можно:
- открыть форму на редактирование какого-то события
- что-то там поменять
- не закрывая форму удалить это событие по клику на иконку 
- нажать save
- datastore.js:197 Uncaught TypeError: Cannot read properties of undefined (reading 'id')

2021-11-02 09:49 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			this.app.callEvent(constants.EVENTS.FILTER_ACTIVITIESTABLE, [id]);
не нужен глобальный ивент, если он и вызывается, и обрабатывается в одном и том же файле

2021-11-02 09:49 UTC, kullias commented on sources/views/activitiesViews/table.js
> +			this.app.callEvent(constants.EVENTS.FILTER_ACTIVITIESTABLE, [id]);
как я уже писала - обработчик в метод и вызываем этот метод

2021-11-02 10:03 UTC, kullias commented on sources/views/contactsViews/form.js
> +		}
и фотка все так же не сбрасывается :) сбрось темплейту src

2021-11-02 10:05 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					if (id) this.filter("#ContactID#", id);
правильнее говоря, this - это джет вью, экземпляр класса

2021-11-02 10:09 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +			this.app.callEvent(constants.EVENTS.FILTER_ACTIVITIESTABLE, [id]);
да, это нелогично, исправил

2021-11-02 10:29 UTC, kullias approved these changes

2021-11-02 10:29 UTC, kullias commented on sources/views/activitiesViews/table.js
> +				onAfterFilter: () => (this.contactId ? this.filterTable(this.contactId) : false)
проверка в методе уже есть, тут не надо)

2021-11-02 10:31 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +				onAfterFilter: () => (this.contactId ? this.filterTable(this.contactId) : false)
точно)

2021-11-02 11:04 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +		}
почему-то form.isDirty() при изменении только фото = false

2021-11-02 11:10 UTC, kullias commented on sources/views/contactsViews/form.js
> +		}
а это потому что нету контрола с name:"Photo"
самый простой совет что могу дать - дропнуть эту проверку на isDirty
начинание хорошее, но тогда  придется писать свою проверку на изменение фото
что впрочем можно сделать как альтернатива

2021-11-02 11:13 UTC, kullias commented on sources/views/contactsViews/form.js
> +		}
вообще я когда-то писала кастомный "контрол" для фоток
https://github.com/webix-hub/doctor-appointment-demo/blob/master/sources/webix/photo.js
использование https://github.com/webix-hub/doctor-appointment-demo/blob/4ae65932ae263dc27bf46c09df7770b6210a3108/sources/views/information.js#L43
не к тому что надо обязательно сюда, а просто как еще один вариант как можно решить эту проблему

2021-11-02 11:14 UTC, astoliarenko commented on sources/views/contactsViews/form.js
> +		}
да, я приходил к этому раньше) пришел опять перед твоим комментом))

2021-11-02 11:39 UTC, kullias commented on sources/views/activitiesViews/editwindow.js
> +			form.clear();
у тебя эти две строчки + clearValidation повторяются по коду минимум 3 раза
лучше бы вынести в метод hideWindow и везде вызывать его

2021-11-02 11:42 UTC, kullias approved these changes

2021-11-02 11:42 UTC, merged