Building a basic CRM: step three
astoliarenko/webix-jet-test-project-1 pull request #3
Opened 2021-11-05 11:19 UTC by astoliarenko

2021-11-05 15:31 UTC, kullias requested changes

2021-11-05 15:31 UTC, kullias commented on sources/views/activitiesViews/table.js
> +						return (startCurWeekStr <= activityDateStr) && (activityDateStr < endCurWeekStr);
даты вообще вполне хорошо сами по себе (объекты) сравниваются через <, <=, >, >=
то есть достаточно найти начало и конец недели и сравнить ту дату, что есть, с ними
это равенство == не работает, но для этого есть webix.Date.equal

2021-11-05 15:31 UTC, kullias commented on sources/views/contacts.js
> +				if (obj[key].toString().toLowerCase().indexOf(filterValue) !== -1) match = true;
стоит выходить из цикла при первом true
лишняя работа

2021-11-05 15:31 UTC, kullias commented on sources/views/contacts.js
> +			if (obj.Birthday && (filterValue.length === 5)) {
крайне маловероятно что где-то в полях будут > < =, поэтому можно "забить" эти символы под поиск по году
и тогда мб стоит сразу проверить что в начале текста есть что-то из этих трех символов и если есть, дальше смотреть
в тексте есть год - проверяем на ДР
нету года - return false

2021-11-05 15:31 UTC, kullias commented on sources/views/contacts.js
> +							break;
можно наверное просто сразу return true

2021-11-05 15:31 UTC, kullias commented on sources/views/contacts.js
> +			if (obj.Phone && (obj.Phone === filterValue)) return true;
undefined не будет равен любой строке, так что необязательно проверять, есть ли в поле значение
кроме того сравнивать на строго совпадение номера телефона мб жестоко
может indexOf? там строки вроде

2021-11-05 15:31 UTC, kullias commented on sources/views/settings.js
> +		const param = this.app.getService("locale");
param?
locale

2021-11-05 15:31 UTC, kullias commented on sources/views/settings.js
> +			localId: "idddd",
плохая идея такие айди давать

2021-11-05 15:31 UTC, kullias commented on sources/views/settings.js
> +				param.setLang(this.$$("idddd").getValue());
кроме того, можно обычную ф-ю использовать и ссылаться на этот контрол как this

2021-11-07 22:28 UTC, astoliarenko commented on sources/locales/ru.js
> +	"type to find matching contacts": "тип для поиска сравнения контактов",
введите для того чтобы найти подходящие контакты :)

2021-11-07 22:31 UTC, astoliarenko commented on sources/views/activities.js
> +		const table = new ActivitiesTableView(this.app);
ну в этом случае так

2021-11-07 22:35 UTC, astoliarenko commented on sources/views/activities.js
> +		this.tabbarValue = "all";
я ведь с его помощью отслеживаю таббар какой выбран, те когда вызывается filterDtByTabbar() я его меняю

2021-11-07 22:37 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +						if (obj.DateObj) return obj.DateObj.getMonth() === currentMonth;
там был еще год? не заметил((

2021-11-07 22:38 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +						if (obj.DateObj) return obj.DateObj.getMonth() === currentMonth;
ааа мол еще и на год проверить, ну это да)

2021-11-07 22:40 UTC, astoliarenko commented on sources/views/activitiesViews/table.js
> +						return obj.DateObj < currentDateObj;
логично, да

2021-11-07 22:47 UTC, astoliarenko commented on sources/views/activities.js
> +		const table = new ActivitiesTableView(this.app);
ну вообще потом ниже я не могу обратиться к методу класса от инстанса если просто ActivitiesTableView.

2021-11-08 06:23 UTC, astoliarenko commented on sources/views/settings.js
> +				{},
скроллы и без спейсеров по Х включаются вроде здесь

2021-11-08 06:50 UTC, astoliarenko commented on sources/views/contacts.js
> +			if (obj.Birthday && (filterValue.length === 5)) {
так в полях > < = не будет, это же для выбора по году, мол хочу все контакты моложе 2021 года

2021-11-08 08:06 UTC, astoliarenko commented on sources/views/settings.js
> +		const param = this.app.getService("locale");
в примере так было, я не переименовывал переменную

2021-11-08 08:23 UTC, astoliarenko commented on sources/views/contacts.js
> +			if (obj.Birthday && (filterValue.length === 5)) {
я тебя не понял сразу)

2021-11-08 09:15 UTC, kullias commented on sources/views/settings.js
> +		const param = this.app.getService("locale");
а в каком примере? в доке не нахожу поиском

2021-11-08 09:32 UTC, kullias commented on sources/views/activities.js
> +		const table = new ActivitiesTableView(this.app);
ясно. вообще более традиционный способ вызывать методы дитяти - положить дитя в subview с именем
а потом this.getSubView("name").Method()
но ладно, пусть будет тогда конструктор

2021-11-08 09:32 UTC, kullias commented on sources/views/activities.js
> +		this.tabbarValue = "all";
в классе таблицы видела, да. а в этом классе он как используется?

2021-11-08 09:50 UTC, astoliarenko commented on sources/views/settings.js
> +		const param = this.app.getService("locale");
глянул в доке тоже не нашел. Давно было, еще на jet-start я так делал, записывал сервис в переменную тк использовал его ниже 2 раза.

2021-11-08 11:33 UTC, kullias commented on sources/views/settingsViews/window.js
> +		form.clear();
эти же три строчки повторяются в хэндлере Cancel
самое лучшее - вынести их в метод и вызывать его в обоих случаях

2021-11-08 11:33 UTC, kullias commented on sources/views/settingsViews/window.js
> +		const form = this.$$(constants.SETTINGS_VIEW.VIEW_IDS.FORM_ID);
в init() можно сохранить в this.form и обращаться везде к ней

2021-11-08 11:33 UTC, kullias commented on sources/views/settingsViews/window.js
> +		form.clear();
hideWindow типа

2021-11-08 11:38 UTC, kullias commented on sources/views/settings.js
> +				{},
я скорее к тому что таблицам места мало, а эти штуки его занимают

2021-11-08 12:01 UTC, astoliarenko commented on sources/views/contacts.js
> +				return false;
на то он и называется форEACH )

2021-11-08 12:15 UTC, astoliarenko commented on sources/views/contactsViews/details.js
> +		if (Birthday) birthday = Birthday.length === 10 ? Birthday : Birthday.slice(0, 10);
c dateToStr в момент написания данного "костыля" не был близко знаком)

2021-11-08 15:24 UTC, kullias commented on sources/views/activitiesViews/table.js
> +	filterDtByAll() {
под 1 строчку заводить метод смысла особо нет, но ладно

2021-11-08 15:57 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					case "all":
а как насчет обработать эту опцию вне прохода по всем айтемам? в начале метода проверить что выбрана эта опция и вызвать ресет фильтра (table.filter())

2021-11-08 15:57 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					case "all":
а чтоб "не сбились" встроенные фильтры - table.filterByAll()

2021-11-08 15:57 UTC, kullias commented on sources/views/contacts.js
> +					match = true;
а можно просто return true и не надо потом `if (match) return true;`

2021-11-08 17:36 UTC, kullias approved these changes

2021-11-08 17:36 UTC, kullias commented on sources/views/activitiesViews/table.js
> +					case "all":
да, тут я погорячилась, потому что нехорошо так делать из метода, который вызывается потом после вызова filterByAll

2021-11-08 17:53 UTC, kullias approved these changes

2021-11-09 11:07 UTC, uladzislaukumakou approved these changes

2021-11-10 10:17 UTC, merged